language: php

php:
  - 7.0
  - 7.1
  - nightly

sudo: false

install:
  - git clone https://github.com/krakjoe/pthreads.git;
    pushd pthreads;
    git checkout master;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=pthreads.so" >> "$(php -r 'echo php_ini_loaded_file();')"
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls dev-master
  - vendor/bin/coveralls -v --exclude-no-stmt
